name: PKAAdventure
version: 0.1.0
main: com.pkadev.pkaadventure.Main
depend: [ProtocolLib, LibsDisguises]
commands:
  pka:
    usage: /pka help
    description: Used for most commands
permissions:
  pkaadventure.premium:
    description: Premium permission
    default: false