name: PKAAdventure
version: 0.9.0
main: com.pkadev.pkaadventure.Main
commands:
  pka:
    usage: /pka help
    description: Used for most commands
  team:
    usage: /team
    description: Team commands
permissions:
  pkaadventure.premium:
    description: Premium permission
    default: false